name: Keep Render Alive

on:
  schedule:
    - cron: '*/5 * * * *' # Pinga a cada 5 Minutos na url da Render

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render backend
        run: curl https://ecommerce-fullstack-eslx.onrender.com
